services:

  postgres:
    image: postgres:15
    container_name: telemetry-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: telemetry
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./infrastructure/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - telemetry-net


  redis:
    image: redis:7
    container_name: telemetry-redis
    ports:
      - "6379:6379"
    volumes:
      - ./infrastructure/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - telemetry-net

  mqtt:
    image: eclipse-mosquitto:2
    container_name: telemetry-mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./infrastructure/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - telemetry-net

  auth-service:
    build:
      context: .                     
      dockerfile: apps/auth-service/Dockerfile
    container_name: telemetry-auth
    ports:
      - "5003:5003"
    depends_on:
      - postgres
    networks:
      - telemetry-net

  device-service:
    build:
      context: .
      dockerfile: apps/device-service/Dockerfile
    container_name: telemetry-device
    ports:
      - "5002:5002"
    depends_on:
      - postgres
      - redis    
    networks:
      - telemetry-net

  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - device-service
      - auth-service
      - telemetry-service
    networks:
      - telemetry-net

  telemetry-service:
    build:
      context: .
      dockerfile: apps/telemetry-service/Dockerfile
    container_name: telemetry-service
    ports:
      - "5001:5001"
    depends_on:
      - postgres
      - redis
    networks:
      - telemetry-net



networks:
  telemetry-net:      